- name: Rollback ACLs on Cisco devices
  hosts: all
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Remove ACL
      ios_config:
        lines:
          - "no {{ item.lines | join('\nno ') }}"
      with_items: "{{ acls }}"
