- name: Rollback VLANs on Cisco switches
  hosts: all
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Remove VLANs
      ios_config:
        lines:
          - "no vlan {{ item.id }}"
      with_items: "{{ vlans }}"
